# Cargo configuration file

# Configure linker settings
[target.x86_64-unknown-linux-gnu]
linker = "gcc"

# Use the default system linker
[build]
rustflags = []

# Silence warnings
[term]
quiet = false
